title: CPU
series:
  - name: System
    unit: '%'
    description: 
    color: BRIGHT_RED
    dataChannel: java.lang:type=OperatingSystem.SystemCpuLoad+PERCENTAGE
  - name: Process
    unit: '%'
    description: 
    color: BRIGHT_YELLOW
    dataChannel: java.lang:type=OperatingSystem.ProcessCpuLoad+PERCENTAGE
   